### ISSUE TITLE
64bit

### ISSUE THREAD

**Issue by caspahouzer** [sideshowcoder/jpgcompressor#4]
Could you be so kind to update this module to 64bit architecture?

**Comment by sideshowcoder** [comment]
I'm currently not using it, but I will look into it any pointers what is needed for this would be helpful if you have any :)

**Comment by caspahouzer** [comment]
I can prepare the project for 64bit and do all the things for you.

My problem only: after doing all 64bit changes, the python build fails with an error not complaining to my changes

```
The following build commands failed:
	CompileC build/jpgcompressor.build/Release-iphoneos/jpgcompressor.build/Objects-normal/armv7/ComSideshowcoderJpgcompressorModule.o Classes/ComSideshowcoderJpgcompressorModule.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/jpgcompressor.build/Release-iphoneos/jpgcompressor.build/Objects-normal/armv7s/ComSideshowcoderJpgcompressorModule.o Classes/ComSideshowcoderJpgcompressorModule.m normal armv7s objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/jpgcompressor.build/Release-iphoneos/jpgcompressor.build/Objects-normal/arm64/ComSideshowcoderJpgcompressorModule.o Classes/ComSideshowcoderJpgcompressorModule.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)
```

I don't know where the problem is. But I can create a pull request with my changes to bring you on the way

**Comment by sideshowcoder** [comment]
Awesome! I will take a look later tonight when I'm off work. :+1:

**Comment by caspahouzer** [comment]
Thanks :+1:

**Comment by sideshowcoder** [comment]
Please see the latest master and tell me if it works as expected :)

**Comment by caspahouzer** [comment]
Thanks for your work. Will tell asap

- Sebastian 

Sent from my iPhone

**Comment by caspahouzer** [comment]
Works great. Thank you!

- Sebastian 

Sent from my iPhone
