### ISSUE TITLE
64bit... again...

### ISSUE THREAD

**Issue by caspahouzer** [sideshowcoder/jpgcompressor#7]
I know, I did the PR, but it doesn't work.

I did it like announced here: http://www.appcelerator.com/blog/2014/11/alpha-version-of-titanium-sdk-64-bit-support-now-available/

and here

https://jira.appcelerator.org/browse/TIMOB-18065

But the architecture remains to "armv7 i386"

Do you have an idea?

**Comment by sideshowcoder** [comment]
No idea really, sorry :( probably best check with the Titanium guys...

**Comment by rborn** [comment]
Hi guys, 
Trying to use v 0.5.2 but it still reports armv7 i386 only.

I'll take a look and make a PR.

**Comment by caspahouzer** [comment]
:+1:

**Comment by rborn** [comment]
#9 should fix this

**Comment by sideshowcoder** [comment]
:+1:
